service: serverless-project-sample

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage}
  versionFunctions: false
  timeout: 60

package:
  individually: true
  exclude:
  - .webpack
  - coverage/**
  - .circleci/**
  - .nyc_output/**
  - tmp/**
  - .git/**
  - .serverless/**
  - .env

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  environment:
    stage:
      dev: DEV
      sandbox: SANDBOX
      prod: PROD
    stageLowercase:
      dev: dev
      sandbox: sandbox
      prod: prod
    config:
      dev:
        region: 530465772375
      sandbox:
        region: 530465772375
      prod:
        region: 530465772375
  region: ${opt:region, self:provider.region}
  accountId: ${self:custom.environment.config.${self:provider.stage}.region}

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions: ${file(./sls/functions.yml)}

# you can add CloudFormation resource templates here
resources:
 Resources: ${file(./sls/resources.yml)}
